### PR TITLE
Backend cleanup for oadoi

### PR DESCRIPTION
**Pull request by wetneb**
First part of the work to kill proaixy and switch to Crossref + OAdoi only.

### CODE REVIEW

**Comment by eocarragain** [comment]
+1 As a downstream consumer of dissemin, great to have clarity on the underlying sources in use, so consolidating on Crossref + OADOI makes sense

**Comment by wetneb** [comment]
@eocarragain it's going to take a while before dissemin is fully in sync with both sources, but it's in progress!

**Comment by eocarragain** [comment]
@wetneb sure. Does this mean that awareness of articles available through researchgate will be going away from dissemin?

**Comment by wetneb** [comment]
No, their records will stay, but the preferred pdf_url of papers will likely change to urls obtained from OAdoi.

**Comment by eocarragain** [comment]
Thanks!

**Pull request merged**
