### PR TITLE
[fix] change OAB URL to stable and https

### PR DESCRIPTION
**Pull request by jibe-b**
See https://github.com/OAButton/discussion/issues/790

### CODE REVIEW

**Comment by jibe-b** [comment]
@wetneb Are the papers requested through the OpenAccessButton recorded?

**Comment by wetneb** [comment]
@jibe-b No we do not have any tracking at all (no analytics either btw).

**Comment by jibe-b** [comment]
Great thing :)

**Comment by jibe-b** [comment]
I asked because until now the request couldn't be succesful as the redirection was to the dev instance of the OAB. So there might be few one that have been started but failed.

Too late ;)

**Comment by wetneb** [comment]
yeah it would be a good reason to actually have some sort of tracking, I suppose…

**Pull request merged**
