### PR TITLE
Add OSF interface

### PR DESCRIPTION
**Pull request by stephno**
It is now possible to deposit papers on OSF Preprints _via_ https://api.osf.io/v2/

### CODE REVIEW

**Comment by wetneb** [comment]
Even the test coverage increased! O_O

**Comment by PLMir** [comment]
🙌🙌🙌 Formidable !
Excellent travail 👌
👍👍 
👏👏
🐤 Félicitations !

**Comment by stephno** [comment]
@wetneb Yes! But I think there’s still something to do with it. It is possible that it doesn’t handle properly `test_form_with_no_subject`, regarding the problem we’ve got lately. Nevertheless, it doesn’t prevent anybody from depositing a paper, so that’s cool. :)

**Comment by wetneb** [comment]
Yes that is something I'll investigate before we push it on prod - but that should not be a problem for testing.

**Comment by wetneb** [comment]
Let's merge this!!

**Pull request merged**
