### PR TITLE
Fix Codacy major errors

### PR DESCRIPTION
**Pull request by Phyks**
WIP, I should review this and outcome of tests first.

For the record, it addresses https://app.codacy.com/app/dissemin/dissemin/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJQeXRob24iXX0seyJpZCI6IkNhdGVnb3J5IiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6WyJFcnJvciJdfSx7ImlkIjoiUGF0dGVybiIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbbnVsbF19XQ==.

### CODE REVIEW

**Comment by wetneb** [comment]
Whoops, I'm responsible for a lot of these!
On the longer term I would like to improve the depositing tests with proper mocking so that we can re-enable them, which would bring coverage up and avoid some of these.

**Comment by Phyks** [comment]
Tests are still passing, should be fine to merge I think. Could use a second pair of eyes for review though :)

**Comment by Phyks** [comment]
@wetneb Is there anything i should be doing on this one?

**Comment by wetneb** [comment]
@Phyks sorry I think I was just waiting for Travis to complete!

**Pull request merged**
