### PR TITLE
Human-friendly slugs in URLs

### LINKED ISSUE #185: Better URLs with slugified names
Suggestions:
* http://dissem.in/researcher/3257/ should be something like http://dissem.in/r/3257/Bernard-Julia
* http://dissem.in/paper/108847/ should be something like http://dissem.in/p/108847/Gravitational_duality_near_de_Sitter_space
and so on…

Add HTTP redirects from the old URLs to the new ones.

### PR DESCRIPTION
**Pull request by Lysxia**
Resolves #185 for papers, researchers and publishers.

- `paper/123` becomes `p/123/title-of-paper`
- `researcher/123` becomes `r/123/name-of-researcher`
- `publisher/123` becomes `b/123/name-of-publisher`

Slugs are currently generated dynamically from names/titles, as that was the simplest to do. They could be stored in a database with little effort; the advantage would be that we can then edit them if needed.

### CODE REVIEW

**Comment by wetneb** [comment]
Nice!
One comment: wouldn't it be better to bind the old urls to redirects instead of the views themselves? So that search engines can switch to the new URLs, for instance. I think in general it is better to ensure that a page is only available under one canonical URL, for indexing purposes. It will also make it easier to disrupt support for the old URLs one day (as late as possible, of course).

**Comment by Lysxia** [comment]
The views take care of the redirection!

**Comment by wetneb** [comment]
But but but… that's beautiful!

**Comment by Lysxia** [comment]
OK I broke some tests because the URLs moved.

**Comment by Lysxia** [comment]
Well at least the tests pass now. I'll add some more.

**Pull request merged**
