### PR TITLE
skeleton.html: Added closing div on wrapper element

### PR DESCRIPTION
**Pull request by NikolaJankovic**
Issue #460 - the paragraph tags are valid but the closing div was missing.

### CODE REVIEW

**Comment by a3nm** [comment]
Hi there! Thanks a lot for trying to fix this bug. :) I had a look and I don't think this closing tag should be added to skeleton.html. I think it should be in faq.html and others. I have added it, but now other issues are popping up...

**Comment by NikolaJankovic** [comment]
Hey, the issue is popping up in faq.html but only because it inherits from skeleton.html where the element with the wrapper id is located. 

Can you let me know which new issues are arising?

**Comment by a3nm** [comment]
I think the div with id "wrapper" is correctly closed in the skeleton, despite the misguiding message from the W3C validator. The div that is not closed is in faq.html (and other files), with id "actualContent".

The new issues are caused by lists in faq.html that are in "p" tags and should be outside of them. I'm working on it now.

**Comment by a3nm** [comment]
OK, I was able to fix these problems, and now the page [is valid](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdissem.in%2Ffaq).

Thanks again for pushing us to fix this bug! I'm very sorry that we couldn't merge your pull request because the closing tag had to be added at another place. Please feel free to fix any other markup glitches if you find some.

**Comment by wetneb** [comment]
@NikolaJankovic Thank you so much for your PR!

**Pull request closed without merging**
