### PR TITLE
Ideas for a rework of main search form

### PR DESCRIPTION
**Pull request by Phyks**
Looking at https://dissem.in/, I was thinking that:

- The Dissemin logo is never used on the website except for the favicon. Therefore, it might not be well associated with Dissemin by users.
- The "Search" button lacks contrast with the rest of the search bar.
- We sometimes use "dissemin" (small letters) and sometimes "Dissemin" (capitalized).
- The search form might not allow easy discovery of all of its possibilities. See #661.

Here is a quick draft of a rework, let me know what you think about it. 

Screenshot_2019-03-28 Accueil - Dissemin

Some questions I have so far:

- [x] Is "Dissemin" or "dissemin" the correct/expected spelling?
- [x] There are many different logos out there, all different. The one from CAPSH website https://association.dissem.in/files/grue_blue_hres.png has a light blue, different from the dissemin favicon https://dissem.in/static/favicon/android-icon-192x192.png and the Twitter one seems to be even darker https://pbs.twimg.com/profile_images/636410533399425024/svih65R2_400x400.png. Which one is the current one? We should probably homogeneize this.

### CODE REVIEW

**Comment by wetneb** [comment]
About dissemin vs Dissemin, no strong feelings for me (we used to try to enforce the lowercase initially, I think, but in the end I find it more natural with a capital letter as it is visually clearer that it is a proper noun). I agree with all other changes.

**Comment by Phyks** [comment]
No longer a WIP. Here is the result.

Index page:

Screenshot_2019-03-29 Accueil - Dissemin

New advanced search page:
Screenshot_2019-03-29 Advanced search - Dissemin(1)


Search results with the form:
Screenshot_2019-03-29 Papiers - Dissemin


This fixes #661 as well as #678 and #354.

**Comment by Phyks** [comment]
Note, the only question remaining (on my side) is the logo question (different logos with different background colors).

**Comment by wetneb** [comment]
@Phyks aaawwww. Jaw droppingly amazing.

Concerning the logo, I am not sure! Is there a version you prefer? We can decide it is the official one and replace the others elsewhere.

**Comment by Phyks** [comment]
I don't like much the current one in the favicon, I feel like the blue background does not connect with anything Dissemin related (dark blue, but not the same one as the dominant blue on dissem.in).

The Twitter one is the same blue as the one we already use everywhere (CAPSH/Dissemin etc). Maybe this is the best choice?

Fwiw, here is how it looks like in the navbar:

Capture d’écran 2019-03-29 à 12 26 18

The light blue one from CAPSH website looks nice also in the navbar, but this should not be the reason to choose it as the logo conveys much more identity than just its effect in the navbar.

Capture d’écran 2019-03-29 à 12 22 01

**Comment by a3nm** [comment]
No strong opinion about the logo; I agree it's a good idea to include it on the website. The rest of the rework looks great to me. :)

**Comment by Phyks** [comment]
I pushed an extra commit to update the favicons.

For https://association.dissem.in/files/grue_blue_hres.png, it could be replaced by 
grue_blue_hres

**Comment by wetneb** [comment]
@Phyks great!!! Feel free to merge when appropriate and I'll be very excited to deploy it :)

**Comment by Phyks** [comment]
Thanks! I'll probably not be much available until Monday, maybe not the safest thing to do to deploy right now :p

**Comment by beckstefan** [comment]
Couldn't we do the last:Doe first:John put into the advanced search in doing separate fields for last and first name? This would not require any quotes, I think.

And most important: Big thumbs up from me!

**Comment by Phyks** [comment]
> And most important: Big thumbs up from me!

Thanks!


> Couldn't we do the last:Doe first:John put into the advanced search in doing separate fields for last and first name? This would not require any quotes, I think.

It's slightly more difficult than this, since this field can be used to look for multiple authors. So it would mean having separate last/first names. I'm not sure this would be much easier for users then and I'd personnally rather try to keep a single field as much as possible.

**Comment by beckstefan** [comment]
Ah, I see. Thanks for the explanation.

Would it work to dynamically add new author name fields? I mean, per standard one author with fields for last and first name and behind that a Plus-Button/Add-Author-Button to add another author, which generates a new set of a tuple for last and first name, via JS? So then it would be clear which first name corresponds to which last name.

**Comment by Phyks** [comment]
Updated on http://association.dissem.in/. Let's merge this one.

I created https://github.com/dissemin/dissemin/issues/696 to track the discussions on the UX of the search field, which would deserve a bit more work in my opinion.

**Pull request merged**
